### ISSUE TITLE
package 'libsurvive_ros2' not found

### ISSUE THREAD

**Issue by imcnanie** [asymingt/libsurvive_ros2#3]
Trying to run the containerized version of this project, have you encountered an error like this before? I'm not a docker expert, so this could be obvious.

```
~/libsurvive_ros2$ docker compose up
[+] Building 0.0s (0/0)                                                                              
[+] Running 1/0
 ✔ Container libsurvive_ros2-libsurvive_ros2-1  Created                                         0.0s 
Attaching to libsurvive_ros2-libsurvive_ros2-1
libsurvive_ros2-libsurvive_ros2-1  | Package 'libsurvive_ros2' not found: "package 'libsurvive_ros2' not found, searching: ['/opt/ros/humble']"
libsurvive_ros2-libsurvive_ros2-1 exited with code 1

```

**Comment by asymingt** [comment]
Thanks for reporting this! Let me see if I can replicate and fix for you.

**Comment by asymingt** [comment]
@imcnanie I've posted a potential fix to branch `asymingt/fix-docker-bug`. Can you confirm that it works for you?

**Comment by imcnanie** [comment]
@asymingt Just tried it works great, then I used `docker compose build --build-arg ROS_DISTRO=iron` to build for iron and I can see the frames in rviz2 on my local machine! Thank you, feel free to close the issue.

**Comment by asymingt** [comment]
Fixed in https://github.com/asymingt/libsurvive_ros2/pull/4
